### ISSUE TITLE
Home Assistant: Zeroconf failure "no buffer space available"

### ISSUE THREAD

**Issue by scottsweb** [scottsweb/ham#53]
When re-creating the Home Assistant container I often have troubles with Zeroconf. This breaks discovery of certain devices like Chromecasts. The main error seems to be:

> No buffer space available

The fix seems to be increasing `igmp_max_memberships`: https://sysctl-explorer.net/net/ipv4/igmp_max_memberships/. This is detailed here: 

https://stackoverflow.com/questions/46727211/oserror-105-no-buffer-space-zeroconf

The following commands worked for me:

```
sudo sysctl -w net.ipv4.igmp_max_memberships=40
sudo systemctl restart avahi-daemon
```

Just documenting for my future self, hope it helps someone else too.

**Comment by ishults** [comment]
I had this same problem and this solved it for me, thank you!
