### ISSUE TITLE
Home Assistant: Resume of Vacuum UI

### ISSUE THREAD

**Issue by scottsweb** [scottsweb/ham#60]
https://www.home-assistant.io/integrations/vacuum.xiaomi_miio/

The vacuum popup has a button for resume but it doesn't work. Using `start` clears the current cleaning plan rather than resuming. 

Related? https://github.com/home-assistant/core/issues/31906

**Comment by chasebolt** [comment]
I also am experiencing this issue. There is no way to resume after pausing my Roborock S6.

**Comment by klim123123** [comment]
Same problem here with Roborock S5 Max. Can't resume cleaning after pause
vacuum.start - clears the current cleaning plan and start cleaning everything.
vacuum.start_pause - no reaction

**Comment by scottsweb** [comment]
@klim123123 Thanks for sharing that, it works well for me too!
